import { Check, Globe2, LockKeyhole, Save, UserRound } from "lucide-react";
import { useState } from "react";
import { Avatar, Button, Card, Input, PageTitle, Select } from "../components/ui-primitives";

export default function Settings() {
  const [saved, setSaved] = useState(false);
  const [name, setName] = useState("Ari Mendoza");
  const [email, setEmail] = useState("ari@northstar.studio");
  const [language, setLanguage] = useState("English");
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <div className="page-container"><PageTitle eyebrow="Workspace" title="Settings" description="The small choices that make this workspace feel like yours." action={<Button onClick={save} data-testid="button-save-settings">{saved ? <><Check size={15} />Saved</> : <><Save size={15} />Save changes</>}</Button>} />
    <div className="settings-layout"><div className="space-y-6"><Card><div className="settings-heading"><span className="stat-icon"><UserRound size={17} /></span><div><h2>Member profile</h2><p>This is how you appear across the workspace.</p></div></div><div className="profile-edit"><Avatar initials="AM" className="large" /><div><button className="text-link" data-testid="button-change-avatar">Change avatar</button><p className="text-xs text-muted-foreground mt-1">Initials are shown to your team.</p></div></div><div className="settings-fields"><label className="field-label">Name<Input value={name} onChange={e => setName(e.target.value)} data-testid="input-settings-name" /></label><label className="field-label">Work email<Input value={email} onChange={e => setEmail(e.target.value)} type="email" data-testid="input-settings-email" /></label><label className="field-label">Preferred language<Select value={language} onChange={e => setLanguage(e.target.value)} data-testid="select-settings-language"><option>English</option><option>Spanish</option><option>French</option><option>Portuguese</option></Select></label></div></Card><Card><div className="settings-heading"><span className="stat-icon blue"><Globe2 size={17} /></span><div><h2>Conversation defaults</h2><p>Help extraction meet your team where it is.</p></div></div><div className="preference-row"><div><p className="font-semibold text-sm">Keep original language visible</p><p className="text-xs text-muted-foreground">Show a source transcript alongside the execution brief.</p></div><button className="toggle is-on" onClick={e => e.currentTarget.classList.toggle("is-on")} aria-label="Toggle original language" data-testid="button-toggle-original-language"><span /></button></div><div className="preference-row"><div><p className="font-semibold text-sm">Gentle deadline reminders</p><p className="text-xs text-muted-foreground">Surface upcoming work without adding noise.</p></div><button className="toggle is-on" onClick={e => e.currentTarget.classList.toggle("is-on")} aria-label="Toggle deadline reminders" data-testid="button-toggle-reminders"><span /></button></div></Card></div><Card className="security-card"><LockKeyhole size={20} /><p className="eyebrow mt-5">Workspace trust</p><h2>Built for the real stuff.</h2><p>Your conversations stay inside your workspace. Only the people you invite can see projects and extracted tasks.</p><div className="security-line"><Check size={14} />No public links</div><div className="security-line"><Check size={14} />Member-level access</div><div className="security-line"><Check size={14} />Original context retained</div></Card></div>
  </div>;
}
